### listas y matrices creadas con la libreria de numpy
##### aqui veremos algunos codigos que son la forma de crear o interpretar en python las listas y matrices 

In [ ]:
import numpy as np # importamos numpy y en todos los siguientes ejercicios numpy se va a llamar np

In [ ]:
escalar = np.array(42) # en este caso se crea una lista pero que solo almacena un numero el 42 en este caso 
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [ ]:
vector = np.array([30, 29, 25, 42, 40, 36, 20]) # en esta caso se crea una lista con numeros 
print(type(vector))
print(vector)

<class 'numpy.ndarray'>
[30 29 25 42 40 36 20]


In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) # aqui creamos un array 3x3 en este caso con los numeros del 1 al 9
print(type(matriz))
print(matriz)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]]) # se crea un tensor 3d que esto es una lista de listas de listas 
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [6]:
array_arange = np.arange(10) # el .arange sirve para crear un array con valores en un rango 
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
eye_matriz = np.eye(6) # esto imprime una matriz en este caso 6x6
print(eye_matriz)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [8]:
diag = np.diag([1,45,67,333,4566]) # aqui hacemos una matriz diagonal pero especificando nosotros los numeros que estan en la diagonal
print(diag)

[[   1    0    0    0    0]
 [   0   45    0    0    0]
 [   0    0   67    0    0]
 [   0    0    0  333    0]
 [   0    0    0    0 4566]]


In [9]:
random = np.random.random((2,3)) # imprime numeros randoms en una matriz 3x2 entre numeros del 0 al 1
print(random)

[[0.29335151 0.8680471  0.35304473]
 [0.78741546 0.54423051 0.20323926]]


In [10]:
random = np.random.random((2,3))   # valores entre 0 y 1
matriz = 5 + (10 - 5) * random     # escala al rango [5, 10]

print(matriz)

[[5.61284922 8.58685314 6.59587541]
 [9.92900481 8.34146004 8.2112842 ]]
