### Broadcasting
El broadcasting sirve para combinar arrays que tienen diferente cantidad de valores entre ellos esto para poder hacer ecuaciones o fusiones entre los arrays 

In [1]:
import numpy as np

In [ ]:
# en este caso se esta uniendo un array de 3 valores multiplicado por un array de un solo valor esto solo para hacer la prueba de que si se pueden unir dos arrays de diferentes tamanios
precios = np.array([100,200,300])
descuento = np.array([0.9])       
precios_descuento = precios * descuento
print(precios_descuento)

[ 90. 180. 270.]


In [ ]:
# unimos un array con una matriz y en este caso se puede decir que son iguales ya que el array es de 3 valores y la matriz es 3x3 entonces al primer valor de la matriz de cada una de sus filas 
# se le van a sumar 10 a la segunda 20 y a la tercera 30 
precios = np.random.randint(100,500, size=(3,3))
descuento = np.array([10,20,30])
precio_sumado = precios + descuento
print(precios)
print(precio_sumado)

[[145 401 439]
 [443 266 316]
 [170 311 340]]
[[155 421 469]
 [453 286 346]
 [180 331 370]]


In [19]:
# de esta forma puede compara un array de precios aplicandole iva con mas de un iva 
precios = np.array([100,200,300,400,500,600,700,800,900,1000])
iva = np.array([0.15 , 0.19 , 0.25])
precio_con_iva = precios[:, np.newaxis] * (1 + iva)
print(precio_con_iva)


[[ 115.  119.  125.]
 [ 230.  238.  250.]
 [ 345.  357.  375.]
 [ 460.  476.  500.]
 [ 575.  595.  625.]
 [ 690.  714.  750.]
 [ 805.  833.  875.]
 [ 920.  952. 1000.]
 [1035. 1071. 1125.]
 [1150. 1190. 1250.]]


In [ ]:
array = np.array([1,2,3,4,5])
print(np.all(array > 0)) # todos los elementos deben ser mayores a 0


True


In [ ]:
print(np.any(array > 4)) # algun elemento es mayor a 4

True


### concatenacion
sirve para unir dos o mas arrays en uno solo con el orden que queramos 


In [28]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,3])

concatenar = np.concatenate((array1, array2))
print(concatenar)

[1 2 3 4 5 3]


In [31]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.array([7,8,9])

concatenar = np.concatenate((array1, array3, array2))
print(concatenar)
# asi se organiza el array de forma acendente
concatenar.sort()
print(concatenar)
#tambien se puede de forma decendente
concatenar.sort()
concatenar = concatenar[::-1]
print(concatenar)

[1 2 3 7 8 9 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


### stacking
apila arrays o da otra dimencionalidad especificando que queremos que agan 

In [34]:
stakear_verticalmente = np.vstack((array1, array2))
print(stakear_verticalmente)

[[1 2 3]
 [4 5 6]]


In [36]:
stakear_horizontalmente = np.hstack((array1, array2))
print(stakear_horizontalmente)

[1 2 3 4 5 6]


### split
division de los arrayas en arrays mas pequenios

In [2]:
array3 = np.arange(1,11)
split_array = np.array_split(array3, 3)
print(array3)
print(split_array)

#de esta forma se pueden usar estos nuevos arrays llamandoslos desde sus indices 
a = split_array[0]   # primer array
b = split_array[1]   # segundo array
c = split_array[2]   # tercer array

print(a)
print(b)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
[1 2 3 4]
[5 6 7]
[ 8  9 10]
