### conteo de respuestas unicas
en numpy podemos usar codigo para contar la cantidad de respuestas identicas como se aria en una encuesta

In [3]:
import numpy as np

In [4]:
respuestas = np.array(['bueno', 'regular', 'malo','excelente','malo','malo','malo','excelente','bueno','regular'])

print(np.unique(respuestas)) # las diferentes respuestas únicas que hay en el array 

['bueno' 'excelente' 'malo' 'regular']


In [ ]:
# se usan dos variables para un mejor orden porque si usamos una sola habran dos arrays en esa sola variable pero asi mostrara las dos de una mejor forma
elementos_unicos, cuenta = np.unique(respuestas, return_counts=True) # devuelve una tupla con los elementos unicos y la cantidad de veces que se repite cada uno
print(elementos_unicos)
print(cuenta)

# si solo usamos una variable veremos con en una hay dos arrays por eso arriba se usan dos variable para que en la primera se guarden los valores unicos y en la segunda la cantidad de cada uno 
ejemplo = np.unique(respuestas, return_counts=True) # devuelve una tupla con los elementos unicos y la cantidad de veces que se repite cada uno
print(ejemplo)

['bueno' 'excelente' 'malo' 'regular']
[2 2 4 2]
(array(['bueno', 'excelente', 'malo', 'regular'], dtype='<U9'), array([0, 3, 2, 1]), array([2, 2, 4, 2]))


### copias y vistas 
funcionamiento de las vistas 

In [ ]:
array_x = np.arange(1,10)
vista = array_x[1:3]
print(array_x)
print(vista)
array_x[1:3] = [10,20] # la vista cambia al igual que el array 
print(array_x)
print(vista)

[1 2 3 4 5 6 7 8 9]
[2 3]
[ 1 10 20  4  5  6  7  8  9]
[10 20]


creacion de una copia 

In [ ]:
array_x = np.arange(1,10)
copia = array_x[[1,2]] # crea una copia del array
print(array_x)
print(copia)
array_x[1:3] = [10,20] # la copia no se modifica porque es independiente
print(array_x)
print(copia)

[1 2 3 4 5 6 7 8 9]
[2 3]
[ 1 10 20  4  5  6  7  8  9]
[2 3]
