#### idexacion y slicing sirven para proporcionar una manera rapida y flexible para manejar los datos

In [1]:
import numpy as np  

In [2]:
array = np.array([10, 20, 30, 40, 50])
print(array[3]) # accede a la posicion seleccionada de el array 
print(array[-1])

40
50


In [3]:
print(array[1:3]) # trae los elementos en las posiciones 2 y 3 porque iniciamos desde el 1 que en programacion es el 2

[20 30]


In [4]:
print(array[1:8]) # trae los elementos en las posiciones 2, 3, 4, 5 y 6 aunque nos pacemos en la especificacion de los elementos que queremos que nos traiga 
print('array pero trayendolo de atras hacia adelante')
print(array[-1:-7]) # no trae ningun elemento porque de esta manera no funciona

[20 30 40 50]
array pero trayendolo de atras hacia adelante
[]


In [5]:
bool_index = array > 25 # vemos que elementos son mayores a 25
print(array[bool_index]) # muestra los valores en el array que sean mayores a 25
print(bool_index) # muestra de forma de booleano los que si cumplen o no con esta condicion
print(type(bool_index)) # muestra que tipo de dato es bool_index

[30 40 50]
[False False  True  True  True]
<class 'numpy.ndarray'>


In [6]:
index = [2,0,4]
print(array[index]) # trae los elementos en las posiciones 3, 1 y 5 del array

[30 10 50]


In [7]:
array2 = np.random.randint(2, 50, size=(3,3))
print(array2)
print(array2[1,1]) # trae el elemento en la posicion fila 1 columna 2

[[34 32 31]
 [22 11  8]
 [24 43  6]]
11


In [10]:
print(array2[0:2, 0:3]) # trae las filas 0 y 1 y las columnas 0, 1 y 2

[[34 32 31]
 [22 11  8]]
