### Manipulación de Matrices y Arrays en NumPy: Transponer, Invertir y Aplanar
esto sirve para resolver sistemas de ecuaciones tambien sirve para algoridmos de procesamientos de selniales 

In [1]:
import numpy as np

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
transpuestas = matriz.T # la t nos dice que las transpone y cambia los lugares de la matriz 
print(matriz)
print(transpuestas)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#se puede hacer siempre que la dimension sea la misma en ejemplo esta esta tenemos 12 deatos que caben en matrices 3x4 o 2x6 pero no caben en una 3x5
array = np.arange(1,13)
reshape = array.reshape(3,4) # cambia la forma del array a 3 filas y 4 columnas
reshape2 = array.reshape(2,6) # cambia la forma del array a 2 filas y 6 columnas
print(array)
print(reshape)
print(reshape2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
reversiva = array[::-1] # invierte el array
print(array)
print(reversiva)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
# el flatinf sirve para aplanar matrices y dejarlas en array
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) # matriz de 2 dimenciones 
aplanamiento = matriz.flatten() # aplana la matriz a una dimension
print(matriz)
print(aplanamiento)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
